#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys


def check():
    print("Number of arguments: %d" % len(sys.argv))
    print("Arguments List: %s" % str(sys.argv))


def get_msg(idx=0):
    """"""
    msg = [
        'Boa! Continue trabalhando campeão!',
        'Boa! Continue o bom trabalho com a força, Jedi!',
    ]
    print('\n\033[92m{}\033[0m\n'.format(msg[idx]))


def run():
    """run it."""
    check()
    get_msg(1)


if __name__ == '__main__':  # pragma: no cover
    run()
