#!/usr/bin/python
# -*- coding: utf-8 -*-
"""this run Python 2.7."""
import sys
import random


def check():
    print("Number of arguments: %d" % len(sys.argv))
    print("Arguments List: %s" % str(sys.argv))


def get_msg(idx=0, notfixed=True):
    """"""
    msg = [
        'Boa! Continue trabalhando campeão!',
        'Executado com sucesso.',
        'Boa! Continue o bom trabalho com a força, Jedi!',
    ]
    base = '\n\033[92m{}\033[0m\n'
    if notfixed:
        print(msg[random.randint(0, len(msg)-1)])
    else:
        print(base.format(msg[idx]))


def run():
    """run it."""
    # check()
    get_msg(1)


if __name__ == '__main__':  # pragma: no cover
    run()
