#!/bin/bash

cd docs/; poetry run task docs-build; cd -
git add site
#git config core.hooksPath None
git commit -m "docs: Updated documentation ($(date +%FT%R))"
#git config core.hooksPath .git-hooks/
