#!/bin/bash

MESSAGE=$(cat $1)
COMMITFORMAT="^((feat|feature|fix|bugfix|chore|refactor|docs|style|test|perf|ci|build|revert|other)(\((.*)\))?\!?: #([0-9]+)|(Merge|Bumping|Revert)) (.*)$"
if ! [[ "$MESSAGE" =~ $COMMITFORMAT ]]; then
  message="Your commit was rejected due to the commit message. Skipping..."
  message+="\n\nPlease use the following format:"
  message+="\n<type>(optional scope): #id-issue <description>"
  message+="\n\nExamples:"
  message+="\nfeature: #1234 feature example comment"
  message+="\nfix(ui): #4321 bugfix example comment"
  message+="\nfix!: #4321 chore example comment with possible breaking change"
  message+="\nchore!: #4321 chore example comment with possible breaking change"
  message+="\nrefactor(chore)!: #4321 chore example comment with possible breaking change"
  message+="\n\nMore details on docs/user_guide/CONVENTIONAL_COMMITS.md or https://www.conventionalcommits.org/pt-br/v1.0.0/"
  echo -e "\033[1;31mERROR: $message\033[0m";
  exit 1
fi
