#!/bin/bash

MESSAGE=$(cat "$1")
COMMITFORMAT="^((feature|feat|fix|docs|refactor|test|chore|style|perf|other)\
(\((.*)\))?!?: #([0-9]+)|(Merge|Bumping|docs: Updated documentation\
|style: Applied Code style))\s*(.*)$"
if ! [[ "$MESSAGE" =~ $COMMITFORMAT ]]; then
  echo "Your commit was rejected due to the commit message. Skipping..."
  echo ""
  echo "Please use the following format:"
  echo "<type>: #<issue-id> <message comment>"
  echo "example:"
  echo "feature: #1234 feature example comment"
  echo "fix(ui): #4321 bugfix example comment"
  echo "docs: Updated documentation"
  echo "style: Applied Code style"
  echo ""
  echo "More details on docs/COMMITS.md"
  exit 1
fi
