name: Tests CI/CD    #Success run

on:
  pull_request:
    branches: [main, dev]
  push:
    branches-ignore:
      - tags

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install

    - name: Test with tox
      run: poetry run tox

    - name: Generate coverage report
      run: |
        poetry run pytest -v --cov=./incolumepy --cov-report=xml
